services:
  basicapi:
    image: ${DOCKER_REGISTRY-}basicapi
    build:
      context: .
      dockerfile: BasicApi/Dockerfile
    container_name: basicapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "${HOST_PORT:-8080}:8080"  #  тут менять порты пример 8090:8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    restart: unless-stopped