// Generates src/shared/api/schema.d.ts from the backend's OpenAPI snapshot.
// Run after the snapshot changes: npm run gen:api. A test fails while the file is stale.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import openapiTS, { astToString } from 'openapi-typescript'

export const SNAPSHOT = fileURLToPath(
  new URL('../../BasicApi.IntegrationTests/Snapshots/openapi.json', import.meta.url),
)
export const OUTPUT = fileURLToPath(new URL('../src/shared/api/schema.d.ts', import.meta.url))

const HEADER = '// Generated by scripts/gen-api.mjs from the OpenAPI snapshot. Do not edit.\n\n'

/** Schema names referenced (transitively) from the given roots. */
function reachable(doc, roots) {
  const seen = new Set()
  const visit = (node) => {
    if (Array.isArray(node)) return node.forEach(visit)
    if (!node || typeof node !== 'object') return
    const ref = node.$ref
    if (typeof ref === 'string' && ref.startsWith('#/components/schemas/')) {
      const name = ref.slice('#/components/schemas/'.length)
      if (!seen.has(name)) {
        seen.add(name)
        visit(doc.components.schemas[name])
      }
    }
    Object.values(node).forEach(visit)
  }
  visit(roots)
  return seen
}

/**
 * The server writes every property of a response (null included) unless it is marked
 * x-omitted-when-null, but the document has no `required`. Every schema except the request-only
 * ones gets those properties required, so a response field is never `T | undefined`; request
 * bodies keep their optional fields.
 */
function markResponsesRequired(doc) {
  const operations = Object.values(doc.paths).flatMap((item) => Object.values(item))
  const requestOnly = reachable(doc, operations.map((op) => op.requestBody ?? null))
  for (const name of reachable(doc, operations.map((op) => op.responses ?? null))) {
    requestOnly.delete(name)
  }

  for (const [name, schema] of Object.entries(doc.components.schemas)) {
    if (!requestOnly.has(name) && schema.properties) {
      // x-omitted-when-null: the server leaves the field out instead of writing null.
      schema.required = Object.entries(schema.properties)
        .filter(([, property]) => !property['x-omitted-when-null'])
        .map(([key]) => key)
    }
  }
  return doc
}

export async function generate() {
  const doc = markResponsesRequired(JSON.parse(readFileSync(SNAPSHOT, 'utf8')))
  const ast = await openapiTS(doc, {
    alphabetize: true,
    rootTypes: true,
    rootTypesNoSchemaPrefix: true,
  })
  return HEADER + astToString(ast)
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  writeFileSync(OUTPUT, await generate())
  console.log(`written ${OUTPUT}`)
}
