<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- AnyCPU (default) allows native execution on both x64 and ARM64 Linux -->
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="Npgsql" Version="10.0.2" />
		<PackageReference Include="FluentMigrator" Version="8.0.1" />
		<PackageReference Include="FluentMigrator.Runner" Version="8.0.1" />
		<PackageReference Include="FluentMigrator.Runner.Postgres" Version="8.0.1" />
	</ItemGroup>

</Project>
