// User-facing texts for the server's error codes (docs/api-contract-changes.md, error code reference).

export const ERROR_TEXTS: Record<string, string> = {
  VALIDATION_ERROR: 'Проверьте введённые данные',
  MESSAGE_EMPTY: 'Пустое сообщение',
  MESSAGE_TOO_LONG: 'Слишком длинное сообщение',
  INVALID_CURSOR: 'Не удалось загрузить: устаревшая ссылка на страницу',
  INVALID_QUERY: 'Слишком короткий запрос',
  TOO_MANY_MESSAGES: 'Можно переслать не больше 100 сообщений',
  REPLY_TARGET_NOT_FOUND: 'Сообщение, на которое вы отвечаете, удалено',
  INVALID_REACTION: 'Такую реакцию поставить нельзя',
  INVALID_ENTITIES: 'Неверное форматирование или упоминание',
  SELF_CHAT: 'Нельзя написать самому себе — используйте «Избранное»',
  INVALID_TITLE: 'Неверное название',
  TOO_MANY_FOLDERS: 'Папок не может быть больше 20',
  TOO_MANY_MEMBERS: 'В группе слишком много участников',
  NOT_A_GROUP: 'Это действие доступно только в группах',
  INVALID_PERMISSIONS: 'Это право можно дать только администратору',
  INVALID_MEDIA: 'Файл не подходит',
  TOO_MANY_PINNED: 'Закрепить можно не больше 10 чатов',
  INVALID_ALBUM: 'В одном сообщении — до 10 файлов одного вида',
  INVALID_AVATAR: 'Аватар должен быть фотографией',
  FILE_TOO_LARGE: 'Файл слишком большой',
  UPLOAD_INCOMPLETE: 'Файл не загрузился до конца',
  PASSWORD_TOO_LONG: 'Слишком длинный пароль',
  WRONG_PASSWORD: 'Неверный текущий пароль',
  INVALID_SUBSCRIPTION: 'Браузер не поддерживает уведомления этого сервера',
  INVALID_DISPLAY_NAME: 'Недопустимое имя',
  INVALID_CREDENTIALS: 'Неверный логин или пароль',
  SESSION_REVOKED: 'Сеанс завершён, войдите снова',
  USER_INACTIVE: 'Аккаунт отключён',
  NOT_A_MEMBER: 'Вы не участник этого чата',
  NOT_MESSAGE_AUTHOR: 'Это чужое сообщение',
  EDIT_WINDOW_EXPIRED: 'Сообщение уже нельзя изменить: прошло слишком много времени',
  DELETE_WINDOW_EXPIRED: 'Сообщение уже нельзя удалить у всех: прошло слишком много времени',
  MESSAGE_NOT_EDITABLE: 'Пересланные и служебные сообщения не редактируются',
  PRIVACY_RESTRICTED: 'Пользователь ограничил, кто может ему писать или добавлять его',
  USER_BLOCKED: 'Вы заблокировали этого пользователя — разблокируйте, чтобы писать',
  PERMISSION_DENIED: 'Недостаточно прав',
  ACCESS_DENIED: 'Нет доступа',
  USER_NOT_FOUND: 'Пользователь не найден',
  CHAT_NOT_FOUND: 'Чат не найден',
  FOLDER_NOT_FOUND: 'Папка не найдена',
  DEVICE_NOT_FOUND: 'Устройство уже вышло',
  MEMBER_NOT_FOUND: 'Пользователь не состоит в группе',
  UPLOAD_NOT_FOUND: 'Загрузка не найдена, попробуйте ещё раз',
  ATTACHMENT_NOT_FOUND: 'Файл недоступен',
  MESSAGE_NOT_FOUND: 'Сообщение не найдено',
  USERNAME_TAKEN: 'Этот логин уже занят',
  EMAIL_TAKEN: 'Этот email уже занят',
  REGISTRATION_CLOSED: 'Регистрация на этом сервере закрыта',
  INVITE_INVALID: 'Приглашение не подходит: неверное, уже использовано или истекло',
  INVITES_DISABLED: 'Приглашения на этом сервере выключены',
  TOO_MANY_INVITES: 'Слишком много неиспользованных приглашений',
  USER_ALREADY_EXISTS: 'Такой пользователь уже есть',
  CLIENT_MESSAGE_ID_CONFLICT: 'Не удалось отправить, попробуйте ещё раз',
  TOO_MANY_UPLOADS: 'Слишком много незавершённых загрузок',
  INTERNAL_ERROR: 'Ошибка на сервере, попробуйте позже',
  MEDIA_UNAVAILABLE: 'Файлы на этом сервере отключены',
  PUSH_UNAVAILABLE: 'Уведомления на этом сервере отключены',
}

export const VALIDATION_TEXTS: Record<string, string> = {
  REQUIRED: 'не заполнено',
  MAX_LENGTH: 'слишком длинно',
  MIN_LENGTH: 'слишком коротко',
  INVALID_FORMAT: 'неверный формат',
  OUT_OF_RANGE: 'вне допустимых значений',
  MISMATCH: 'не совпадает',
}

/** Request field (camelCase) -> how the user knows it. */
export const FIELD_NAMES: Record<string, string> = {
  username: 'Логин',
  usernameOrEmail: 'Логин',
  email: 'Email',
  password: 'Пароль',
  currentPassword: 'Текущий пароль',
  newPassword: 'Новый пароль',
  displayName: 'Имя',
  text: 'Текст',
  title: 'Название',
}
